### ISSUE TITLE
64-bit version

### ISSUE THREAD

**Issue by mahfiaz** [monoblaine/MarkdownViewerPlusPlus#1]
Would it be possible to compile and upload a 64-bit version as well? Right now the readme is slightly overpromising in this regard.

**Comment by monoblaine** [comment]
Hey @mahfiaz I've updated the release assets:

https://github.com/monoblaine/MarkdownViewerPlusPlus/releases/tag/v0.9.0

Could you please try the x64 version of the dll and let me know if it works? To be honest, I've not tried that myself. I'm still using the x86 version.

**Comment by mahfiaz** [comment]
It works well. Thanks a lot :)

**Comment by asmwarrior** [comment]
Hi, I just extract the x64 version of the dll, and I copy this dll to replace the old 0.8.x version of my Notepad++ 64bit, but when I start the Notepad++, it shows that:

~~~~
---------------------------
c:\Program Files\Notepad++\plugins\MarkdownViewerPlusPlus\MarkdownViewerPlusPlus.dll
---------------------------
Failed to load

MarkdownViewerPlusPlus.dll is not compatible with the current version of Notepad++.

Do you want to remove this plugin from the plugins directory to prevent this message from the next launch?
---------------------------
Yes(Y)   No(N)   
---------------------------
~~~~

Any ideas?

Thanks. 

I'm using the latest Notepad++ 64bit of version 8.4.6 under Windows 7 64bit. Maybe you plugin is not compatable with Windows 7.

**Comment by monoblaine** [comment]
Hi @asmwarrior, the plugin needs the legacy Edge installed (not the Chromium one). Might that be the reason in your case, by any chance?

**Comment by asmwarrior** [comment]
> Hi @asmwarrior, the plugin needs the legacy Edge installed (not the Chromium one). Might that be the reason in your case, by any chance?

Oh, I really don't know how to install a legacy Edge. If the browser is too big(many be it is bigger than 200M bytes) to install, I think I won't do that. Thanks.

**Comment by monoblaine** [comment]
According to [this page](https://techcommunity.microsoft.com/t5/microsoft-365-blog/new-microsoft-edge-to-replace-microsoft-edge-legacy-with-april-s/ba-p/2114224):

> No, Microsoft Edge Legacy was not available for Windows 7 or Windows 8.X. This will only impact the Windows 10 versions listed previously.

It appears that the legacy Edge was never introduced in Windows 7 anyway. So installing it was never an option, sorry about that.
